[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[dev]
  framework = "#static"
  functionsPort = 8888
  port = 8888
  targetPort = 8888

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "jsonwebtoken"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/protect-content/:splat"
  status = 200
  force = true

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY_ACCOUNT_ID = "686334463bc6a22c3309cee1"